spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus?characterEncoding=utf-8&userSSL=false
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource

mybatis-plus:
  configuration:
    # 配置MyBatis日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #配置MyBatis-Plus操作表的默认前缀
      #table-prefix: t_
      #配置MyBatis-Plus的主键策略
      id-type: auto
  #配置类型别名所对应的包
  type-aliases-package: com.example.mybatisplus.pojo
  #扫描通用枚举的包
  type-enums-package: com.example.mybatisplus.enums
